const TALLYSUCCESS = "tally success";
const MOREPENDINGTHANCONFIRMED = "more pending than confirmed";
const ONEPENDINGANDNOCONFIRMED = "one pending and no confirmed";
const RECEIPTEMAIL = "RECEIPT";
const OTHERCHANNELEMAIL = "OTHERCHANNEL";
const MANUALREQEMAIL = "MANUALREQ";

module.exports = {
  TALLYSUCCESS,
  MOREPENDINGTHANCONFIRMED,
  ONEPENDINGANDNOCONFIRMED,
  RECEIPTEMAIL,
  OTHERCHANNELEMAIL,
  MANUALREQEMAIL,
};
